algolia:
  application_id: "TN8HK9FU3W"
  index_name: "ninterviews"
  files_to_exclude:
    - config.html
    - index.html
    - index.md
    - logs.md
    - pages/**/index.*
    - search.html
  nodes_to_index: "p,h2,h3,h4"
  settings:
    searchableAttributes:
      - title
      - unordered(content)
      - unordered(interviewees)
    attributesToHighlight:
      - content
      - interviewees
      - tags
      - title
author: Xzonn
collections:
  switch:
    output: true
    sort_by: date
  wiiu:
    output: true
    sort_by: date
  3ds:
    output: true
    sort_by: date
  wii:
    output: true
    sort_by: date
  ds:
    output: true
    sort_by: date
  other:
    output: true
    sort_by: date
collections_dir: pages
default_image: https://www.nintendo.co.jp/img/og_nintendo.png
defaults:
  - values:
      layout: "default"
      license: "cc-by-nc-sa-4.0"
      image: https://www.nintendo.co.jp/img/og_nintendo.png
      image_width: 1200
      image_height: 630
  - scope:
      path: "pages/*/index.*"
    values:
      no_date: true
      no_sidenav: true
  - scope:
      path: "pages/*/*.staff.*"
    values:
      no_date: true
      no_index: true
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - ossutil64
  - package.json
  - package-lock.json
  - "*.less"
  - "*.psd"
image_cdn: https://images.xzonn.top/ninterviews
kramdown:
  syntax_highlighter_opts:
    css_class: "highlight"
locale: zh_CN
markdown: kramdown
name: 任天堂开发者访谈保存计划
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
timezone: Asia/Shanghai
title: 任天堂开发者访谈保存计划
url: https://ninterviews.xzonn.top
sass:
  load_paths:
    - css
  sourcemap: always
  style: compressed