algolia:
  application_id: "TN8HK9FU3W"
  index_name: "ninterviews"
collections:
  switch:
    output: true
    sort_by: date
  wiiu:
    output: true
    sort_by: date
  3ds:
    output: true
    sort_by: date
  wii:
    output: true
    sort_by: date
  ds:
    output: true
    sort_by: date
  other:
    output: true
    sort_by: date
collections_dir: pages
defaults:
  - values:
      layout: "default"
      license: "cc-by-nc-sa-4.0"
      head_image_width: 1280
      head_image_height: 720
  - scope:
      path: "*/index.md"
    values:
      no_date: true
      no_sidenav: true
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
kramdown:
  syntax_highlighter_opts:
    css_class: "highlight"
markdown: kramdown
name: 任天堂开发者访谈保存计划
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
timezone: Asia/Shanghai
sass:
  load_paths:
    - css
  sourcemap: always
  style: compressed